### ISSUE TITLE
Installing some software with TrollStore will cause the microphone to be enabled unsuccessfully.

### ISSUE THREAD

**Issue by hrgfdz** [opa334/TrollStore#768] opened 2024-04-17 13:11 UTC
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

TrollStore installs the Chinese version of WeChat, and occasionally the microphone starts unsuccessfully.

### Current Behavior?

TrollStore installs the Chinese version of WeChat, and occasionally the microphone starts unsuccessfully.

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstaller2

### iOS/iPadOS version

ios 16.6.1

### iDevice Model

iphone 13 pro max

**Comment by khaleddarweesh6** [comment] 2024-04-29 00:46
> ### No Duplicates Issue
> 
> - [X] I'm sure I've searched on the issue tracker before creating one.
> 
> ### Expected Behavior?
> 
> TrollStore installs the Chinese version of WeChat, and occasionally the microphone starts unsuccessfully.
> 
> ### Current Behavior?
> 
> TrollStore installs the Chinese version of WeChat, and occasionally the microphone starts unsuccessfully.
> 
> ### Possible Solution?
> 
> -
> 
> ### Steps to Reproduce
> 
> -
> 
> ### TrollStore Version
> 
> TrollInstaller2
> 
> ### iOS/iPadOS version
> 
> ios 16.6.1
> 
> ### iDevice Model
> 
> iphone 13 pro max
> 
> ### Other info of your environment
> 
> _No response_

**Comment by opa334** [comment] 2024-07-02 09:44
Duplicate of #657

**Closed by opa334** 2024-07-02 09:44 UTC
