### ISSUE TITLE
TrollHelperOTA does not support arm64 iOS 14

### ISSUE THREAD

**Issue by pythonName** [opa334/TrollStore#268] opened 2022-10-10 01:33 UTC
iphone7 , ios14.6 "GTA Car Tracker" crashed when open it.

why?

**Comment by ewgundam** [comment] 2022-10-10 03:31
same issue.iOS14.6

**Comment by pai1233** [comment] 2022-10-10 03:36
same issue IOS 14.1
why

**Comment by daxiewo** [comment] 2022-10-10 05:23
same 14.3

**Comment by tom-snow** [comment] 2022-10-10 05:24
If the prebuilt Trollinstaller2 doesn't work, you can try [building it yourself](https://github.com/opa334/TrollStore/blob/37dcff4fcd29555b9bc5d5bce968ecee02cccdab/install_trollinstaller2.md).


If still not work, please try the methods previously provided in the repository or wait for an update.

**Comment by opa334** [comment] 2022-10-10 05:30
Known issue, TrollInstaller2 unfortunately does not work on iOS 14, use checkra1n + TrollHelper to install it.

For arm64e iOS 14 devices, use https://api.jailbreaks.app/troll64e.

**Comment by RavanGami** [comment] 2022-10-10 05:31
iphone 8 plus not work

**Comment by CubeBag** [comment] 2022-10-10 16:30
Have you thought about reverting the last few commits so the version table is on the homepage again?

**Comment by Git-James23** [comment] 2022-10-11 14:58
same issue, 6s, iOS 14.4 
Hope boss update soon!!!

**Comment by opa334** [comment] 2022-10-11 16:16
Probably not possible to fix. The issue is that iOS 14 does not seem to support launching arm64v8 binaries :/

**Comment by xoyi** [comment] 2022-10-11 16:21
> 可能无法修复。问题是 iOS 14 似乎不支持启动 arm64v8 二进制文件：/，所以只有 arm64e 版本（https://api.jailbreaks.app/troll64e）有效

same with others, 6s p ,ios 14.5.1 , i use checkra1n + TrollHelper can use

**Comment by Git-James23** [comment] 2022-10-11 16:24
Bad news😭so only jailbreak can work?

**Comment by xiuxianchengdi** [comment] 2022-10-12 01:35
@Git-James23 You can use SSHRD (a8-a11) to install it on ios14+ without jailbreak

**Comment by opa334** [comment] 2022-11-27 00:09
Closing as this is impossible because arm64v8 are not supported by the iOS 14 kernel.

**Closed by opa334** 2022-11-27 00:09 UTC

**Comment by opa334** [comment] 2022-12-20 11:48
> iphone 13pro ios 15.6 installed "GTA Car Tracker" from https://api.jailbreaks.app/troll64e, not Opening!

readme exists to read it

**Comment by gamer191** [comment] 2023-08-03 11:50
> You can use SSHRD (a8-a11) to install it on ios14+ without jailbreak

Does that method permanently delete the tips app (or whichever app you choose) or can it be reverted?
