### ISSUE TITLE
UTM fails to launch

### ISSUE THREAD

**Issue by osy** [opa334/TrollStore#102] opened 2022-09-08 03:27 UTC
After installing UTM (https://github.com/utmapp/UTM/releases) and trying to launch it, I see the following error in the Console:

```
default	18:06:29.490712-0700	kernel	App Store Fast Path -> /private/var/containers/Bundle/Application/C5A47390-D305-4C31-916A-4B12085CA566/UTM.app/UTM
error	18:06:29.491688-0700	runningboardd	Process start failed with Error Domain=NSPOSIXErrorDomain Code=85 "Bad executable (or shared library)" UserInfo={NSLocalizedDescription=Launchd job spawn failed}
```

**Comment by heinekenpsx** [comment] 2022-09-08 04:00
Read this
https://getutm.app/install/
That error is not from TrollStore

**Comment by osy** [comment] 2022-09-08 04:35
Yes, I wrote that. The error is not from trollstore but from how trollstore is signing it.

**Comment by opa334** [comment] 2022-09-08 09:14
Duplicate of #49

**Closed** 2022-09-08 09:14 UTC

**Comment by osy** [comment] 2022-09-08 15:45
@opa334 I’m on the latest build btw. Where you able to run UTM without issue? Is it a config issue on my side?
