### ISSUE TITLE
Allow Notifications popup is not coming in any app.

### ISSUE THREAD

**Issue by baziex** [opa334/TrollStore#21] opened 2022-09-03 09:50 UTC
TrollStore installed App Settings also not showing in iOS Settings.

There is no Installed App names in Settings>Notifications section.

Please try to fix this as soon as possible.

**Comment by DetachHead** [comment] 2022-09-03 23:11
Duplicate of #17 (though this one has a better title)

**Comment by wen704** [comment] 2022-09-04 02:32
I have a idea
Maybe can replace same package id app when install app from trollstore
Just like trollstore replace tips or other system app
Maybe this way can fix app's notification

**Comment by opa334** [comment] 2022-09-04 10:19
https://github.com/opa334/TrollStore/issues/38

**Closed by opa334** 2022-09-04 10:19 UTC
