### ISSUE TITLE
Problems caused by specific bundle id

### ISSUE THREAD

**Issue by Tiaoge-tou** [opa334/TrollStore#371] opened 2022-11-25 12:01 UTC
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

When I try to install an ipa, no matter how it is installed (trollstore or signature), it should appear on the desktop.

### Current Behavior?

When I install an ipa, its bundle id has (com.apple), it doesn't appear on the desktop.

### Possible Solution?

Any ipa modifies the bundle id with (com.apple) will cause this problem, and this problem cannot be solved by uicache or restarting the device. The bundle id that has had a problem will not be displayed on the desktop, so you can only modify again bundle id

### Steps to Reproduce

install it with trollstore,uninstall the ipa with (com.apple) at the beginning of bundle id, and then install the same ipa by signature, and the ipa cannot be displayed on the desktop,Reuse trollstore to overwrite the installation,It will only be displayed in the trollstore list, not on the desktop. 

### TrollStore Version

1.3.5-1.4.4

### iOS/iPadOS version

14.3

### iDevice Model

iphone12 pro max

**Comment by Tiaoge-tou** [comment] 2022-11-25 12:10
For example (com.apple.tiao) Or any other beginning with (com.apple)

**Comment by opa334** [comment] 2022-11-25 21:08
Please for the love of god, use a different identifier. There is not a single reason for using `com.apple` at the start of your identifier.

**Comment by Tiaoge-tou** [comment] 2022-11-26 00:24
> Please for the love of god, use a different identifier. There is not a single reason for using `com.apple` at the start of your identifier.

When this bundle id has gone wrong, will it never be able to appear on the desktop? Unless the restore device is erased.

**Comment by opa334** [comment] 2022-11-26 13:39
Please open this tar in TrollStore to update to it, then rebuild icon cache. Let me know if the problem is fixed afterwards.

https://www.mediafire.com/file/pybjnod1gj9dfy9/TrollStore.tar/file

**Comment by Tiaoge-tou** [comment] 2022-11-27 05:36
Sorry! I saw your reply very late,this update fixed my problem,the disappearing bundle id can appear on the desktop again,thank you very much.

**Comment by Tiaoge-tou** [comment] 2022-11-27 05:36
> Please open this tar in TrollStore to update to it, then rebuild icon cache. Let me know if the problem is fixed afterwards.
> 
> https://www.mediafire.com/file/pybjnod1gj9dfy9/TrollStore.tar/file

Sorry! I saw your reply very late,this update fixed my problem,the disappearing bundle id can appear on the desktop again,thank you very much.

**Comment by opa334** [comment] 2022-11-29 22:39
Fix is also in 1.4.5 beta 1, closing this.

https://twitter.com/opa334dev/status/1597720828711313408

**Closed by opa334** 2022-11-29 22:39 UTC
