### ISSUE TITLE
[Question] Delta emulator cannot working after installed by Trollstore. Only Delta name in Trollstore without icon.

### ISSUE THREAD

**Issue by FlynnYork** [opa334/TrollStore#109] opened 2022-09-08 16:11 UTC

**Comment by Carter1190** [comment] 2022-09-08 16:17
duplicate of #65 maybe

**Comment by FlynnYork** [comment] 2022-09-08 16:19
> delta works fine for me ,where did u get your ipa,provide more details such ad ios 14 or ios 15

IOS 14.2 jailbreak by Taurine.
Delta IPA version:  Delta_1_3_1.

Could you share your IPA for me? I wanna test.

**Comment by FlynnYork** [comment] 2022-09-08 16:21
> duplicate of #65 maybe

I don't have same issue. #65 
It's working right installing under jailbreak environment.

**Comment by MarsWonderBoy** [comment] 2022-09-09 20:56
> duplicate of #65 maybe

Heyhey, just to clear things up -- my issue was never about performance, but only if the app retained its icon image. However, I will add that I never had issues running the Delta.ipa. It played my games fine and I got it from rileytestut's official github.

**Comment by opa334** [comment] 2022-09-29 19:12
Can't reproduce

**Closed by opa334** 2022-09-29 19:12 UTC
