### ISSUE TITLE
i think little but critical problem

### ISSUE THREAD

**Issue by SudoFormatAll** [opa334/TrollStore#120] opened 2022-09-10 08:37 UTC
hello, I found the problem of TrollStore
after installing ALL, ANY, applications they "like" half-not exist for the OS.
1. Apps do not appear in system settings. because of that you cannot change permissions and advanced settings that are only available there. some apps have critical settings only there.
2. application folders with files are not visible through PC in programs such as imazing, 3uTools. everytime you need to perform moving operations using as an intermediary those folders that are visible and only on the iOS device.

ipadpro a12Z iOS15.1

**Comment by opa334** [comment] 2022-09-10 11:52
1. not fixable, trollstore apps are registered as system apps and system apps don't show up in settings
2. known but unsure if fixable, spoofing ah hoc signed in the newest version has improved it but it still fails

**Comment by SudoFormatAll** [comment] 2022-09-10 12:48
1. it's sad to hear this... but there also some system apps like siri, mail, etc. are displayed in the system settings. maybe can borrow the method from them? no way?...

2. sadness x2...hope you can solve this soon

**Comment by opa334** [comment] 2022-09-10 21:31
also 2 is a duplicate of https://github.com/opa334/TrollStore/issues/75

**Closed by opa334** 2022-09-10 21:31 UTC
