### ISSUE TITLE
麦克风问题

### ISSUE THREAD

**Issue by Luyao666888** [opa334/TrollStore#808] opened 2024-07-02 03:21 UTC
Hello, occasionally when using apps in the Chinese region with Trolls 2, the microphone fails to start properly, and the issue occurs frequently when using WeChat. Given that WeChat is a widely used messaging app in China, the impact is significant. I hope you can address this issue (Trolls 1 does not have this problem). Please, thank you.🙏

**Comment by Hwatu** [comment] 2024-07-02 09:07
ditto, Please, thank you.🙏

**Comment by opa334** [comment] 2024-07-02 09:44
Duplicate of #657

**Closed by opa334** 2024-07-02 09:44 UTC
