### ISSUE TITLE
ppsspp Emulator

### ISSUE THREAD

**Issue by MrBrownie124** [opa334/TrollStore#82] opened 2022-09-06 03:08 UTC
when installing ppsspp its supposed to make a file for you to put your games in, in troll store it dose not work. To test this i installed it with sideloadly and it worked as usual.

**Comment by notbugme** [comment] 2022-09-09 02:14
the same issue ...

**Comment by H1deMe** [comment] 2022-09-10 10:08
Same here
1.0.8 still not fixed
But retroarch is good working

**Comment by opa334** [comment] 2022-09-10 11:56
duplicate of https://github.com/opa334/TrollStore/issues/75

**Closed by opa334** 2022-09-10 11:56 UTC
