### ISSUE TITLE
### No Duplicates Issue

### ISSUE THREAD

**Issue by chanya2534** [opa334/TrollStore#410] opened 2023-01-07 19:19 UTC
### No Duplicates Issue

- [x] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

 When you uninstall TrollStore and click ‘Uninstall Apps’ it should uninstall TrollStore including all the apps.

### Current Behavior?

When I uninstalled TrollStore and clicked ‘Uninstall Apps’ it uninstalled TrollStore but kept the apps installed. When I click on an app theres a button that says ‘Switch to “(null)” Registration’ when it should say ‘Switch to “User” Registration’ and be in system registration. If I uninstall a null registration app it instead looks for a reinstalled version of the app and uninstalls that including apps in a newer version of that same app.

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

1.4.5

### iOS/iPadOS version

iPadOS 15.5 beta 4

### iDevice Model

iPad 8th Generation

_Originally posted by @vilzio in https://github.com/opa334/TrollStore/issues/403_

_Originally posted by @chanya2534 in https://github.com/opa334/TrollStore/issues/409_

**Comment by opa334** [comment] 2023-01-07 20:54
Duplicate of #403 (seriously, what did you expect???)

**Closed by opa334** 2023-01-07 20:54 UTC
