### ISSUE TITLE
Will you consider adding Chinese support?

### ISSUE THREAD

**Issue by Tzbfire** [opa334/TrollStore#100] opened 2022-09-08 02:25 UTC
Will you consider adding Chinese support?

**Comment by Tzbfire** [comment] 2022-09-08 02:26
会考虑添加汉化支持吗

**Comment by F-Unction** [comment] 2022-09-11 05:03
It is a very easy-to-use tool. I don't think it needs multi-language support.

**Comment by BuLu0208** [comment] 2022-09-27 07:37
我觉得有必要支持中文

**Comment by xiuxianchengdi** [comment] 2022-10-12 01:43
Most of people are using English, why you think it need Chinese?

**Comment by opa334** [comment] 2022-10-29 23:06
Duplicate of #68

**Closed by opa334** 2022-10-29 23:06 UTC

**Comment by bm131488bm** [comment] 2022-11-30 03:25
不影响 也就 几个 简单的 
It doesn't affect just a few simple words
